name: Publish (CSM Foundation Core) Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.event.head_commit.message != 'Initial commit'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: ğŸ”„ Checkout repo
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: ğŸ” Authenticate with GitHub Packages
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
              --name github \
              --username ${{ github.actor }} \
              --password ${{ secrets.PUBLISH_PAT }} \
              --store-password-in-clear-text

      - name: ğŸ“¦ Pack NuGet project
        run: dotnet pack "csm_foundation\csm_foundation_core\CSM Foundation Core\CSM Foundation Core\CSM Foundation Core.csproj" --configuration Release --output ./nupkgs

      - name: ğŸ“¤ Push NuGet package
        run: dotnet nuget push ./nupkgs/*.nupkg --source github --skip-duplicate
